version: '3'  
services:  
  ai-demo:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    image: ai-demo
    ports:  
      - 3002:3000  
    restart: on-failure
    healthcheck:  
      interval: 5s  
      timeout: 2s  
      retries: 3  
      start_period: 10s
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/"]
 
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
